server_name: "localhost"
pid_file: /data/homeserver.pid
listeners:
  - port: 8008
    resources:
    - compress: false
      names:
      - client
      - federation
    tls: false
    type: http
    x_forwarded: true
database:
  name: sqlite3
  args:
    database: /data/homeserver.db
log_config: "/data/localhost.log.config"
media_store_path: /data/media_store
registration_shared_secret: "3pM2moO;nASlR12gSSbcVBCbxO9AFuFubCtnscHkt9xU1#G~R+"
report_stats: false
macaroon_secret_key: "sWC=4Zci=I;nL53eH~-kq0LnG87gH^Sf=WKOzW@_IaP*PpGj-;"
form_secret: "ZPe8CIZs+Bem4HzL=fzAb9Asi0El:xc9Rodr3&W-VMfwJy5zWD"
signing_key_path: "/data/localhost.signing.key"
trusted_key_servers:
  - server_name: "matrix.org"

enable_registration: true
enable_registration_without_verification: true
suppress_key_server_warning: true

serve_server_wellknown: true
public_baseurl: "https://localhost/"

app_service_config_files:
  - /data/appservices/brute.yml
  - /data/appservices/echo.yml
